apiVersion: v1
kind: Service
metadata:
  name: k8s-basic-python-service
spec:
  selector:
    app.kubernetes.io/name: basic-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
